### ISSUE TITLE
More informative error message when you didn't add measurement gates

### ISSUE THREAD

**Issue by anapalu** [qilimanjaro-tech/qiboconnection#117]
### Feature details

I don't have enough experience to know whether this is the only case in which it happens, but I've noticed that when a circuit (or a set thereof) does not contain measurement gates, the job immediately fails, without going through the queue. Which is nice. I thus assume that there is some check of the program before queueing that noticed this mistake and turned down the execution. In this case, I assume that the information of where the mistake lies has been collected, and thus maybe it isn't much work to include it in qiboconnection's error message. Since it's the kind of mistake you don't expect to make (because obviously), it may be very helpful to be immediately notified when your cable crosses, your saint goes to the sky or it's your all-dumb-day

### How important would you say this feature is?

1: Not important. Would be nice to have.

**Comment by AlbertMitjans** [comment]
Hi @anapalu, can you provide the code + error message you get when you don't use a measurement gate?

I wasn't aware that this check was in `qiboconnection`. Do we have it? @islegmar @JavierSab @ziiiki

**Comment by anapalu** [comment]
I thought I had taken a screenshot but I can't find it, I'll prepare another notebook and see if I can reproduce the message this Thursday

**Comment by anapalu** [comment]
Indeed there is no error message, but moreover I think this issue was spurious and what really happened is that my jobs got pushed to the beginning of the queue those times, so I will close this entry.
