### ISSUE TITLE
Add description string to job

### ISSUE THREAD

**Issue by anapalu** [qilimanjaro-tech/qiboconnection#122]
### Feature details

Along the lines of what was suggested in issue #121 , having the possibility of attaching a short description to each job would also help find old jobs that we would like to retrieve for some purpose. I believe qiskit has this feature as well. 

### How important would you say this feature is?

1: Not important. Would be nice to have.

**Comment by JavierSab** [comment]
Hi!
Are we thinking in some specific length? eg. stadard sentence (50-100 char), one paragraph (200-250 char),  old-tweet (240 char), new-tweet (280 char), 1,000 char ~2 KB,  max json length (2,097,152 char ~ 4MB)...

**Comment by anapalu** [comment]
I guess standard sentence(50-100 char)  should be fine, people should be able to come up with their own identifying systems. For larger descriptions, if we want to allow the user to store more notes, I would maybe allow one paragraph on a separate variable `description ` or something like this, but this description sounds more like something the user should create on their own elsewhere because they may be interested in updating it later

**Comment by AlbertMitjans** [comment]
I completely agree with your suggestion Javi! I will add an issue and we can refine it tomorrow!
