### ISSUE TITLE
Get queue position when a job is in the queue

### ISSUE THREAD

**Issue by anapalu** [qilimanjaro-tech/qiboconnection#138]
### Feature details

This was implemented before the migration to slurm. Maybe the queue position could also be shown in the api.list_jobs() dataframe (right now status only has "completed" or "queued" entries, it would be nice if the queued ones could contain the queue position).

### How important would you say this feature is?

1: Not important. Would be nice to have.

**Comment by ziiiki** [comment]
Hi, thank you for your suggestion! Nevertheless, if you update qiboconnection to 0.15.2, you should see the position of your job when doing qiboconnection_api.get_job(). Note this position only takes into account QaaS jobs as the API is not aware of the lab ones

**Comment by JavierSab** [comment]
It would be good though to also include it in the list_jobs, specially thinking about the web. I'll try to add this the next time we edit the models for the web

**Comment by anapalu** [comment]
Thank you both!

**Comment by JavierSab** [comment]
Functionality in last release !!
