### ISSUE TITLE
API get_result() method does not inform when job fails

### ISSUE THREAD

**Issue by rsagas** [qilimanjaro-tech/qiboconnection#152]
### Feature details

When querying the API for the result of a job, the call get_result(job_id) returns None for any case that the job did not run.

If the job ran but it failed, it only prints a warning, but it returns None nevertheless. It would be useful for users waiting for their results if this is changed.

That is to say, the function behaves differently for results that need to be waited vs results that have failed and waiting for them is pointless.

### Implementation

I suggest returning either False or raising an Exception

### How important would you say this feature is?

1: Not important. Would be nice to have.

**Comment by islegmar** [comment]
We suggest to use get_job() and from there get the result, instead get_result() directly. Nevertheless, in the future get_result() will ne deprecated
